language: python

python: '3.6'

env:
  - GALAXY_DB_USER=postgres

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv

install:
  - pip install tox

jobs:
  include:
    - name: "Flake8"
      script: tox -e flake8
    - name: "Unit tests"
      script: tox -e py36
      services:
        - docker
        - postgresql
