language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv

install:
  - pip install tox

script: tox

stages:
  - flake8
  - test

jobs:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - stage: flake8
      python: '3.6'
      env: TOXENV=flake8
